package com.example.jroster

import android.util.Log
import java.text.SimpleDateFormat
import java.util.*

class extAirports {

    // Data class to hold all airport data
    data class Airport(
        val name: String,
        val iata: String,
        val icao: String,
        val latLong: String,
        val elevation: String,
        val utcVariation: String,
        val timeZone: String
    ) {
        // Function to get the latitude and longitude as a Pair of Doubles
        val coordinates: Pair<Double, Double>?
            get() {
                val components = latLong.split(",")
                return if (components.size == 2) {
                    val latitude = components[0].trim().toDoubleOrNull()
                    val longitude = components[1].trim().toDoubleOrNull()
                    if (latitude != null && longitude != null) {
                        Pair(latitude, longitude)
                    } else {
                        null
                    }
                } else {
                    null
                }
            }
    }

    // Function to convert ATA/ATD's into a 4-digit string in local time
    fun convertToLocalTime(date: Date, timezoneStr: String): String? {
        return try {
            // Get the timezone from the timezone string
            val timeZone = TimeZone.getTimeZone(timezoneStr)
            val dateFormat = SimpleDateFormat("HH:mm", Locale.getDefault())

            // Set the formatter's timezone to the destination timezone
            dateFormat.timeZone = timeZone

            // Log information for debugging
            Log.d("Airport", "Original date in UTC: ${date}")  // Original date in UTC
            Log.d("Airport", "TimeZone: $timezoneStr")
            Log.d("Airport", "Formatted local time: ${dateFormat.format(date)}")  // Formatted time in local time zone

            // Return the formatted time in the local timezone
            dateFormat.format(date)
        } catch (e: Exception) {
            Log.e("Airport", "Error formatting date", e)
            null
        }
    }


    // Data
    val airports = listOf(
        Airport(name = "", iata = "UTC", icao = "GMT", latLong = "0,0", elevation = "0", utcVariation = "UTC +0", timeZone = "UTC"),
        Airport(name = "Nadi International Airport", iata = "NAN", icao = "NFFN", latLong = "-17.7554, 177.4433", elevation = "59", utcVariation = "UTC +12", timeZone = "Pacific/Fiji"),
        Airport(name = "Rarotonga International Airport", iata = "RAR", icao = "NCRG", latLong = "-21.2022, -159.8056", elevation = "19", utcVariation = "UTC -10", timeZone = "Pacific/Rarotonga"),
        Airport(name = "Albany Airport", iata = "ALH", icao = "YABA", latLong = "-34.9433, 117.8097", elevation = "233", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Alice Springs Airport", iata = "ASP", icao = "YBAS", latLong = "-23.8067, 133.9022", elevation = "1789", utcVariation = "UTC +9.5", timeZone = "Australia/Darwin"),
        Airport(name = "Ballina Byron Gateway Airport", iata = "BNK", icao = "YBNA", latLong = "-28.8339, 153.5622", elevation = "7", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Bathurst Airport", iata = "BHS", icao = "YBTH", latLong = "-33.4094, 149.6519", elevation = "2434", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Brisbane Airport", iata = "BNE", icao = "YBBN", latLong = "-27.3842, 153.1175", elevation = "13", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Broome International Airport", iata = "BME", icao = "YBRM", latLong = "-17.9500, 122.2106", elevation = "56", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Bundaberg Airport", iata = "BDB", icao = "YBUD", latLong = "-24.9039, 152.3192", elevation = "107", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Busselton Margaret River Airport", iata = "BQB", icao = "YBLN", latLong = "-33.6875, 115.4000", elevation = "55", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Canberra Airport", iata = "CBR", icao = "YSCB", latLong = "-35.3069, 149.1950", elevation = "1886", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Cloncurry Airport", iata = "CNJ", icao = "YCCY", latLong = "-20.6683, 140.5047", elevation = "616", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Coffs Harbour Airport", iata = "CFS", icao = "YCFS", latLong = "-30.3206, 153.1161", elevation = "18", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Darwin International Airport", iata = "DRW", icao = "YPDN", latLong = "-12.4147, 130.8767", elevation = "103", utcVariation = "UTC +9.5", timeZone = "Australia/Darwin"),
        Airport(name = "Devonport Airport", iata = "DPO", icao = "YDPO", latLong = "-41.1697, 146.4311", elevation = "33", utcVariation = "UTC +10", timeZone = "Australia/Hobart"),
        Airport(name = "Doomadgee Airport", iata = "DMD", icao = "YDMG", latLong = "-17.9400, 138.8222", elevation = "157", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Emerald Airport", iata = "EMD", icao = "YEML", latLong = "-23.5675, 148.1792", elevation = "624", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Fraser Coast Airport", iata = "HVB", icao = "YHBA", latLong = "-25.3189, 152.8800", elevation = "61", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Gold Coast Airport", iata = "OOL", icao = "YBCG", latLong = "-28.1644, 153.5047", elevation = "21", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Gladstone Airport", iata = "GLT", icao = "YGLA", latLong = "-23.8697, 151.2233", elevation = "68", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name= "Hamilton Island Airport", iata= "HTI", icao= "YBHM", latLong= "-20.3581, 148.9511", elevation= "15", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Hobart International Airport", iata= "HBA", icao= "YMHB", latLong= "-42.8361, 147.5094", elevation= "13", utcVariation= "UTC +10", timeZone= "Australia/Hobart"),
        Airport(name= "Horn Island Airport", iata= "HID", icao= "YHID", latLong= "-10.5867, 142.2903", elevation= "43", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Kalgoorlie-Boulder Airport", iata= "KGI", icao= "YPKG", latLong= "-30.7894, 121.4622", elevation= "1203", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Karratha Airport", iata= "KTA", icao= "YPKA", latLong= "-20.7122, 116.7731", elevation= "29", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Kingscote Airport", iata= "KGC", icao= "YKSC", latLong= "-35.7139, 137.5206", elevation= "24", utcVariation= "UTC +9.5", timeZone= "Australia/Adelaide"),
        Airport(name= "Launceston Airport", iata= "LST", icao= "YMLT", latLong= "-41.5453, 147.2144", elevation= "562", utcVariation= "UTC +10", timeZone= "Australia/Hobart"),
        Airport(name= "Learmonth Airport", iata= "LEA", icao= "YPLM", latLong= "-22.2356, 114.0894", elevation= "19", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Longreach Airport", iata= "LRE", icao= "YLRE", latLong= "-23.4342, 144.2797", elevation= "627", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Lord Howe Island Airport", iata= "LDH", icao= "YLHI", latLong= "-31.5383, 159.0764", elevation= "17", utcVariation= "UTC +10.5", timeZone= "Australia/Lord_Howe"),
        Airport(name= "Mackay Airport", iata= "MKY", icao= "YBMK", latLong= "-21.1717, 149.1797", elevation= "19", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Melbourne Airport", iata= "MEL", icao= "YMML", latLong= "-37.6733, 144.8433", elevation= "434", utcVariation= "UTC +10", timeZone= "Australia/Melbourne"),
        Airport(name= "Mildura Airport", iata= "MQL", icao= "YMIA", latLong= "-34.2292, 142.0864", elevation= "167", utcVariation= "UTC +10", timeZone= "Australia/Melbourne"),
        Airport(name= "Moranbah Airport", iata= "MOV", icao= "YMRB", latLong= "-22.0578, 148.0764", elevation= "776", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Mount Isa Airport", iata= "ISA", icao= "YBMA", latLong= "-20.6639, 139.4886", elevation= "1121", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Newcastle Airport", iata= "NTL", icao= "YWLM", latLong= "-32.7947, 151.8330", elevation= "31", utcVariation= "UTC +10", timeZone= "Australia/Sydney"),
        Airport(name= "Perth Airport", iata= "PER", icao= "YPPH", latLong= "-31.9403, 115.9667", elevation= "67", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Port Hedland International Airport", iata= "PHE", icao= "YPPD", latLong= "-20.3778, 118.6253", elevation= "33", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Port Lincoln Airport", iata= "PLO", icao= "YPLC", latLong= "-34.6053, 135.8800", elevation= "36", utcVariation= "UTC +9.5", timeZone= "Australia/Adelaide"),
        Airport(name= "Proserpine/Whitsunday Coast Airport", iata= "PPP", icao= "YBPN", latLong= "-20.4950, 148.5522", elevation= "79", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Rockhampton Airport", iata= "ROK", icao= "YBRK", latLong= "-23.3819, 150.4753", elevation= "36", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Sunshine Coast Airport", iata= "MCY", icao= "YBSU", latLong= "-26.6033, 153.0910", elevation= "15", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Tamworth Airport", iata= "TMW", icao= "YSTW", latLong= "-31.0839, 150.8464", elevation= "1334", utcVariation= "UTC +10", timeZone= "Australia/Sydney"),
        Airport(name= "Toowoomba Wellcamp Airport", iata= "WTB", icao= "YBWW", latLong= "-27.5583, 151.7931", elevation= "1477", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Townsville Airport", iata= "TSV", icao= "YBTL", latLong= "-19.2525, 146.7647", elevation= "18", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Wagga Wagga Airport", iata= "WGA", icao= "YSWG", latLong= "-35.1653, 147.4667", elevation= "724", utcVariation= "UTC +10", timeZone= "Australia/Sydney"),
        Airport(name= "Whyalla Airport", iata= "WYA", icao= "YWHA", latLong= "-33.0589, 137.5144", elevation= "41", utcVariation= "UTC +9.5", timeZone= "Australia/Adelaide"),
        Airport(name= "Williamtown RAAF Base", iata= "WLM", icao= "YWLM", latLong= "-32.7947, 151.8330", elevation= "31", utcVariation= "UTC +10", timeZone= "Australia/Sydney"),
        Airport(name= "Auckland Airport", iata= "AKL", icao= "NZAA", latLong= "-37.0081, 174.7917", elevation= "23", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Wellington International Airport", iata= "WLG", icao= "NZWN", latLong= "-41.3272, 174.8053", elevation= "41", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Queenstown Airport", iata= "ZQN", icao= "NZQN", latLong= "-45.0211, 168.7392", elevation= "1171", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Dunedin Airport", iata= "DUD", icao= "NZDN", latLong= "-45.9281, 170.1983", elevation= "4", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Hamilton Airport", iata= "HLZ", icao= "NZHN", latLong= "-37.8667, 175.3325", elevation= "172", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Napier Airport", iata= "NPE", icao= "NZNR", latLong= "-39.4658, 176.8683", elevation= "6", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Nelson Airport", iata= "NSN", icao= "NZNS", latLong= "-41.2983, 173.2219", elevation= "17", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "New Plymouth Airport", iata= "NPL", icao= "NZNP", latLong= "-39.0086, 174.1792", elevation= "97", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Palmerston North Airport", iata= "PMR", icao= "NZPM", latLong= "-40.3206, 175.6169", elevation= "151", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Rotorua Airport", iata= "ROT", icao= "NZRO", latLong= "-38.1092, 176.3178", elevation= "935", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Taupo Airport", iata= "TUO", icao= "NZAP", latLong= "-38.7397, 176.0847", elevation= "1335", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Tauranga Airport", iata= "TRG", icao= "NZTG", latLong= "-37.6719, 176.1958", elevation= "13", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Invercargill Airport", iata= "IVC", icao= "NZNV", latLong= "-46.4122, 168.3128", elevation= "5", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Gisborne Airport", iata= "GIS", icao= "NZGS", latLong= "-38.6633, 177.9781", elevation= "15", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Whangarei Airport", iata= "WRE", icao= "NZWR", latLong= "-35.7683, 174.3656", elevation= "133", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Kerikeri Airport", iata= "KKE", icao= "NZKK", latLong= "-35.2628, 173.9122", elevation= "492", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Whakatane Airport", iata= "WHK", icao= "NZWK", latLong= "-37.9206, 176.9142", elevation= "13", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Hokitika Airport", iata= "HKK", icao= "NZHK", latLong= "-42.7136, 170.9853", elevation= "146", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Westport Airport", iata= "WSZ", icao= "NZWS", latLong= "-41.7381,171.5800", elevation= "13", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Timaru Airport", iata= "TIU", icao= "NZTU", latLong= "-44.3028, 171.2256", elevation= "89", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Kaitaia Airport", iata= "KAT", icao= "NZKT", latLong= "-35.0708, 173.2850", elevation= "270", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Paraparaumu Airport", iata= "PPQ", icao= "NZPP", latLong= "-40.9047, 174.9894", elevation= "22", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Ardmore Airport", iata= "AMZ", icao= "NZAR", latLong= "-37.0297, 174.9733", elevation= "111", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Whanganui Airport", iata= "WAG", icao= "NZWU", latLong= "-39.9622, 175.0247", elevation= "27", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Waiouru Military Camp Airport", iata= "WIR", icao= "NZRU", latLong= "-39.4667, 175.6750", elevation= "2671", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Wanaka Airport", iata= "WKA", icao= "NZWF", latLong= "-44.7222, 169.2467", elevation= "1140", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Milford Sound Airport", iata= "MFN", icao= "NZMF", latLong= "-44.6733, 167.9236", elevation= "10", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Chatham Islands / Tuuta Airport", iata= "CHT", icao= "NZCI", latLong= "-43.8103, -176.4575", elevation= "43", utcVariation= "UTC +12.75", timeZone= "Pacific/Chatham"),
        Airport(name= "Kerikeri Airport", iata= "KKE", icao= "NZKK", latLong= "-35.2628, 173.9122", elevation= "492", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Oamaru Airport", iata= "OAM", icao= "NZOU", latLong= "-44.9708, 171.0822", elevation= "99", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Aalborg Airport", iata= "AAL", icao= "EKYT", latLong= "57.0928, 9.8492", elevation= "10", utcVariation= "UTC +1", timeZone= "Europe/Copenhagen"),
        Airport(name= "Aarhus Airport", iata= "AAR", icao= "EKAH", latLong= "56.3000, 10.6190", elevation= "82", utcVariation= "UTC +1", timeZone= "Europe/Copenhagen"),
        Airport(name= "Albuquerque International Sunport", iata= "ABQ", icao= "KABQ", latLong= "35.0402, -106.6092", elevation= "5355", utcVariation= "UTC -7", timeZone= "America/Denver"),
        Airport(name= "Nnamdi Azikiwe International Airport", iata= "ABV", icao= "DNAA", latLong= "9.0068, 7.2632", elevation= "1123", utcVariation= "UTC +1", timeZone= "Africa/Lagos"),
        Airport(name= "Kotoka International Airport", iata= "ACC", icao= "DGAA", latLong= "5.6145, -0.2055", elevation= "205", utcVariation= "UTC 0", timeZone= "Africa/Accra"),
        Airport(name= "Atlantic City International Airport", iata= "ACY", icao= "KACY", latLong= "39.4576, -74.5772", elevation= "75", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Adnan Menderes Airport", iata= "ADB", icao= "LTBJ", latLong= "38.2924, 27.1570", elevation= "412", utcVariation= "UTC +3", timeZone= "Europe/Istanbul"),
        Airport(name= "Addis Ababa Bole International Airport", iata= "ADD", icao= "HAAB", latLong= "8.9779, 38.7993", elevation= "7631", utcVariation= "UTC +3", timeZone= "Africa/Addis_Ababa"),
        Airport(name= "Adelaide Airport", iata= "ADL", icao= "YPAD", latLong= "-34.9450, 138.5306", elevation= "20", utcVariation= "UTC +9.5", timeZone= "Australia/Adelaide"),
        Airport(name= "Málaga Airport", iata= "AGP", icao= "LEMG", latLong= "36.6749, -4.4991", elevation= "52", utcVariation= "UTC +1", timeZone= "Europe/Madrid"),
        Airport(name= "Auckland Airport", iata= "AKL", icao= "NZAA", latLong= "-37.0081, 174.7917", elevation= "23", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Albany International Airport", iata= "ALB", icao= "KALB", latLong= "42.7483, -73.8017", elevation= "285", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Houari Boumediene Airport", iata= "ALG", icao= "DAAG", latLong= "36.6956, 3.2154", elevation= "82", utcVariation= "UTC +1", timeZone= "Africa/Algiers"),
        Airport(name= "Rick Husband Amarillo International Airport", iata= "AMA", icao= "KAMA", latLong= "35.2194, -101.7050", elevation= "3607", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Queen Alia International Airport", iata= "AMM", icao= "OJAI", latLong= "31.7226, 35.9932", elevation= "2395", utcVariation= "UTC +3", timeZone= "Asia/Amman"),
        Airport(name= "Amsterdam Airport Schiphol", iata= "AMS", icao= "EHAM", latLong= "52.3105, 4.7683", elevation= "-11", utcVariation= "UTC +1", timeZone= "Europe/Amsterdam"),
        Airport(name= "Ted Stevens Anchorage International Airport", iata= "ANC", icao= "PANC", latLong= "61.1744, -149.9982", elevation= "151", utcVariation= "UTC -9", timeZone= "America/Anchorage"),
        Airport(name= "Stockholm Arlanda Airport", iata= "ARN", icao= "ESSA", latLong= "59.6519, 17.9186", elevation= "137", utcVariation= "UTC +1", timeZone= "Europe/Stockholm"),
        Airport(name= "Silvio Pettirossi International Airport", iata= "ASU", icao= "SGAS", latLong= "-25.2408, -57.5200", elevation= "292", utcVariation= "UTC -4", timeZone= "America/Asuncion"),
        Airport(name= "Athens International Airport", iata= "ATH", icao= "LGAV", latLong= "37.9364, 23.9445", elevation= "308", utcVariation= "UTC +2", timeZone= "Europe/Athens"),
        Airport(name= "Hartsfield-Jackson Atlanta International Airport", iata= "ATL", icao= "KATL", latLong= "33.6407, -84.4277", elevation= "1026", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Queen Beatrix International Airport", iata= "AUA", icao= "TNCA", latLong= "12.5014, -70.0152", elevation= "60", utcVariation= "UTC -4", timeZone= "America/Aruba"),
        Airport(name= "Austin-Bergstrom International Airport", iata= "AUS", icao= "KAUS", latLong= "30.1945, -97.6699", elevation= "542", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Antalya Airport", iata= "AYT", icao= "LTAI", latLong= "36.8987, 30.8005", elevation= "177", utcVariation= "UTC +3", timeZone= "Europe/Istanbul"),
        Airport(name= "Barcelona-El Prat Airport", iata= "BCN", icao= "LEBL", latLong= "41.2974, 2.0833", elevation= "12", utcVariation= "UTC +1", timeZone= "Europe/Madrid"),
        Airport(name= "Baco Airport", iata= "BCO", icao= "HABC", latLong= "5.7829, 36.5633", elevation= "1715", utcVariation= "UTC +3", timeZone= "Africa/Addis_Ababa"),
        Airport(name= "L.F. Wade International Airport", iata= "BDA", icao= "TXKF", latLong= "32.3640, -64.6797", elevation= "12", utcVariation= "UTC -4", timeZone= "Atlantic/Bermuda"),
        Airport(name= "Bradley International Airport", iata= "BDL", icao= "KBDL", latLong= "41.9389, -72.6832", elevation= "173", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Belgrade Nikola Tesla Airport", iata= "BEG", icao= "LYBE", latLong= "44.8184, 20.3091", elevation= "335", utcVariation= "UTC +1", timeZone= "Europe/Belgrade"),
        Airport(name= "Belfast International Airport", iata= "BFS", icao= "EGAA", latLong= "54.6575, -6.2158", elevation= "268", utcVariation= "UTC 0", timeZone= "Europe/London"),
        Airport(name= "Grantley Adams International Airport", iata= "BGI", icao= "TBPB", latLong= "13.0746, -59.4925", elevation= "168", utcVariation= "UTC -4", timeZone= "America/Barbados"),
        Airport(name= "Bergen Airport, Flesland", iata= "BGO", icao= "ENBR", latLong= "60.2936, 5.2181", elevation= "170", utcVariation= "UTC +1", timeZone= "Europe/Oslo"),
        Airport(name= "Bangor International Airport", iata= "BGR", icao= "KBGR", latLong= "44.8074, -68.8281", elevation= "192", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Birmingham-Shuttlesworth International Airport", iata= "BHM", icao= "KBHM", latLong= "33.5639, -86.7521", elevation= "650", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Billings Logan International Airport", iata= "BIL", icao= "KBIL", latLong= "45.8077, -108.5429", elevation= "3652", utcVariation= "UTC -7", timeZone= "America/Denver"),
        Airport(name= "Bilbao Airport", iata= "BIO", icao= "LEBB", latLong= "43.3011, -2.9106", elevation= "137", utcVariation= "UTC +1", timeZone= "Europe/Madrid"),
        Airport(name= "Bologna Guglielmo Marconi Airport", iata= "BLQ", icao= "LIPE", latLong= "44.5354, 11.2887", elevation= "123", utcVariation= "UTC +1", timeZone= "Europe/Rome"),
        Airport(name= "Nashville International Airport", iata= "BNA", icao= "KBNA", latLong= "36.1245, -86.6782", elevation= "599", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "El Dorado International Airport", iata= "BOG", icao= "SKBO", latLong= "4.7016, -74.1469", elevation= "8361", utcVariation= "UTC -5", timeZone= "America/Bogota"),
        Airport(name= "Boise Airport", iata= "BOI", icao= "KBOI", latLong= "43.5644, -116.2230", elevation= "2871", utcVariation= "UTC -7", timeZone= "America/Boise"),
        Airport(name= "Chhatrapati Shivaji Maharaj International Airport", iata= "BOM", icao= "VABB", latLong= "19.0896, 72.8656", elevation= "39", utcVariation= "UTC +5.5", timeZone= "Asia/Kolkata"),
        Airport(name= "Logan International Airport", iata= "BOS", icao= "KBOS", latLong= "42.3656, -71.0096", elevation= "20", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Brussels Airport", iata= "BRU", icao= "EBBR", latLong= "50.9010, 4.4844", elevation= "184", utcVariation= "UTC +1", timeZone= "Europe/Brussels"),
        Airport(name= "Brasília International Airport", iata= "BSB", icao= "SBBR", latLong= "-15.8697, -47.9208", elevation= "3495", utcVariation= "UTC -3", timeZone= "America/Sao_Paulo"),
        Airport(name= "Budapest Ferenc Liszt International Airport", iata= "BUD", icao= "LHBP", latLong= "47.4392, 19.2611", elevation= "495", utcVariation= "UTC +1", timeZone= "Europe/Budapest"),
        Airport(name= "Buffalo Niagara International Airport", iata= "BUF", icao= "KBUF", latLong= "42.9405, -78.7322", elevation= "727", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Baltimore/Washington International Thurgood Marshall Airport", iata= "BWI", icao= "KBWI", latLong= "39.1754, -76.6684", elevation= "146", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Philip S. W. Goldson International Airport", iata= "BZE", icao= "MZBZ", latLong= "17.5391, -88.3082", elevation= "15", utcVariation= "UTC -6", timeZone= "America/Belize"),
        Airport(name= "Cairo International Airport", iata= "CAI", icao= "HECA", latLong= "30.1219, 31.4056", elevation= "382", utcVariation= "UTC +2", timeZone= "Africa/Cairo"),
        Airport(name= "Guangzhou Baiyun International Airport", iata= "CAN", icao= "ZGGG", latLong= "23.3925, 113.2988", elevation= "50", utcVariation= "UTC +8", timeZone= "Asia/Shanghai"),
        Airport(name= "Netaji Subhas Chandra Bose International Airport", iata= "CCU", icao= "VECC", latLong= "22.6547, 88.4467", elevation= "16", utcVariation= "UTC +5.5", timeZone= "Asia/Kolkata"),
        Airport(name= "Charles de Gaulle Airport", iata= "CDG", icao= "LFPG", latLong= "49.0097, 2.5479", elevation= "392", utcVariation= "UTC +1", timeZone= "Europe/Paris"),
        Airport(name= "Soekarno-Hatta International Airport", iata= "CGK", icao= "WIII", latLong= "-6.1256, 106.6559", elevation= "34", utcVariation= "UTC +7", timeZone= "Asia/Jakarta"),
        Airport(name= "Cologne Bonn Airport", iata= "CGN", icao= "EDDK", latLong="50.8659, 7.1427", elevation= "302", utcVariation= "UTC +1", timeZone= "Europe/Berlin"),
        Airport(name= "Christchurch International Airport", iata= "CHC", icao= "NZCH", latLong= "-43.4889, 172.5335", elevation= "123", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Charleston International Airport", iata= "CHS", icao= "KCHS", latLong= "32.8986, -80.0405", elevation= "46", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Cleveland Hopkins International Airport", iata= "CLE", icao= "KCLE", latLong= "41.4117, -81.8498", elevation= "791", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Charlotte Douglas International Airport", iata= "CLT", icao= "KCLT", latLong= "35.2140, -80.9431", elevation= "748", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "John Glenn Columbus International Airport", iata= "CMH", icao= "KCMH", latLong= "39.9980, -82.8919", elevation= "815", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Cairns Airport", iata= "CNS", icao= "YBCS", latLong= "-16.8858, 145.7552", elevation= "10", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Cochin International Airport", iata= "COK", icao= "VOCI", latLong= "10.1520, 76.4019", elevation= "30", utcVariation= "UTC +5.5", timeZone= "Asia/Kolkata"),
        Airport(name= "Cape Town International Airport", iata= "CPT", icao= "FACT", latLong= "-33.9694, 18.5975", elevation= "151", utcVariation= "UTC +2", timeZone= "Africa/Johannesburg"),
        Airport(name= "Copenhagen Airport", iata= "CPH", icao= "EKCH", latLong= "55.6179, 12.6558", elevation= "17", utcVariation= "UTC +1", timeZone= "Europe/Copenhagen"),
        Airport(name= "Changsha Huanghua International Airport", iata= "CSX", icao= "ZGHA", latLong= "28.1892, 113.2208", elevation= "217", utcVariation= "UTC +8", timeZone= "Asia/Shanghai"),
        Airport(name= "Rafael Núñez International Airport", iata= "CTG", icao= "SKCG", latLong= "10.4424, -75.5130", elevation= "4", utcVariation= "UTC -5", timeZone= "America/Bogota"),
        Airport(name= "Cancún International Airport", iata= "CUN", icao= "MMUN", latLong= "21.0365, -86.8771", elevation= "20", utcVariation= "UTC -5", timeZone= "America/Cancun"),
        Airport(name= "Alejandro Velasco Astete International Airport", iata= "CUZ", icao= "SPZO", latLong= "-13.5357, -71.9388", elevation= "10860", utcVariation= "UTC -5", timeZone= "America/Lima"),
        Airport(name= "Afonso Pena International Airport", iata= "CWB", icao= "SBCT", latLong= "-25.5285, -49.1758", elevation= "2988", utcVariation= "UTC -3", timeZone= "America/Sao_Paulo"),
        Airport(name= "Cardiff Airport", iata= "CWL", icao= "EGFF", latLong= "51.3967, -3.3433", elevation= "220", utcVariation= "UTC 0", timeZone= "Europe/London"),
        Airport(name= "Hazrat Shahjalal International Airport", iata= "DAC", icao= "VGHS", latLong= "23.8433, 90.3978", elevation= "30", utcVariation= "UTC +6", timeZone= "Asia/Dhaka"),
        Airport(name= "Dallas Love Field", iata= "DAL", icao= "KDAL", latLong= "32.8471, -96.8518", elevation= "487", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Julius Nyerere International Airport", iata= "DAR", icao= "HTDA", latLong= "-6.8781, 39.2026", elevation= "182", utcVariation= "UTC +3", timeZone= "Africa/Dar_es_Salaam"),
        Airport(name= "Ronald Reagan Washington National Airport", iata= "DCA", icao= "KDCA", latLong= "38.8512, -77.0402", elevation= "15", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Indira Gandhi International Airport", iata= "DEL", icao= "VIDP", latLong= "28.5562, 77.1000", elevation= "777", utcVariation= "UTC +5.5", timeZone= "Asia/Kolkata"),
        Airport(name= "Denver International Airport", iata= "DEN", icao= "KDEN", latLong= "39.8561, -104.6737", elevation= "5431", utcVariation= "UTC -7", timeZone= "America/Denver"),
        Airport(name= "Dallas/Fort Worth International Airport", iata= "DFW", icao= "KDFW", latLong= "32.8998, -97.0403", elevation= "607", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Dalian Zhoushuizi International Airport", iata= "DLC", icao= "ZYTL", latLong= "38.9657, 121.5386", elevation= "32", utcVariation= "UTC +8", timeZone= "Asia/Shanghai"),
        Airport(name= "Hamad International Airport", iata= "DOH", icao= "OTHH", latLong= "25.2731, 51.6081", elevation= "13", utcVariation= "UTC +3", timeZone= "Asia/Qatar"),
        Airport(name= "Detroit Metropolitan Wayne County Airport", iata= "DTW", icao= "KDTW", latLong= "42.2124, -83.3534", elevation= "645", utcVariation= "UTC -5", timeZone= "America/Detroit"),
        Airport(name= "Dublin Airport", iata= "DUB", icao= "EIDW", latLong= "53.4213, -6.2701", elevation= "242", utcVariation= "UTC 0", timeZone= "Europe/Dublin"),
        Airport(name= "King Shaka International Airport", iata= "DUR", icao= "FALE", latLong= "-29.6144, 31.1197", elevation= "295", utcVariation= "UTC +2", timeZone= "Africa/Johannesburg"),
        Airport(name= "Düsseldorf Airport", iata= "DUS", icao= "EDDL", latLong= "51.2895, 6.7668", elevation= "147", utcVariation= "UTC +1", timeZone= "Europe/Berlin"),
        Airport(name= "Dubai International Airport", iata= "DXB", icao= "OMDB", latLong= "25.2532, 55.3657", elevation= "62", utcVariation= "UTC +4", timeZone= "Asia/Dubai"),
        Airport(name= "Newark Liberty International Airport", iata= "EWR", icao= "KEWR", latLong= "40.6895, -74.1745", elevation= "18", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Ministro Pistarini International Airport", iata= "EZE", icao= "SAEZ", latLong= "-34.8222, -58.5358", elevation= "67", utcVariation= "UTC -3", timeZone= "America/Argentina/Buenos_Aires"),
        Airport(name= "Leonardo da Vinci-Fiumicino Airport", iata= "FCO", icao= "LIRF", latLong= "41.8003, 12.2389", elevation= "13", utcVariation= "UTC +1", timeZone= "Europe/Rome"),
        Airport(name= "Fort Lauderdale-Hollywood International Airport", iata= "FLL", icao= "KFLL", latLong= "26.0726, -80.1527", elevation= "9", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Frankfurt Airport", iata= "FRA", icao= "EDDF", latLong= "50.0379, 8.5622", elevation= "364", utcVariation= "UTC +1", timeZone= "Europe/Berlin"),
        Airport(name= "Owen Roberts International Airport", iata= "GCM", icao= "MWCR", latLong= "19.2928, -81.3578", elevation= "8", utcVariation= "UTC -5", timeZone= "America/Cayman"),
        Airport(name= "Guadalajara International Airport", iata= "GDL", icao= "MMGL", latLong= "20.5218, -103.3112", elevation= "5015", utcVariation= "UTC -6", timeZone= "America/Mexico_City"),
        Airport(name= "Rio de Janeiro/Galeão International Airport", iata= "GIG", icao= "SBGL", latLong= "-22.8089, -43.2436", elevation= "28", utcVariation= "UTC -3", timeZone= "America/Sao_Paulo"),
        Airport(name= "Glasgow Airport", iata= "GLA", icao= "EGPF", latLong= "55.8719, -4.4331", elevation= "26", utcVariation= "UTC 0", timeZone= "Europe/London"),
        Airport(name= "Göteborg Landvetter Airport", iata= "GOT", icao= "ESGG", latLong= "57.6628, 12.2798", elevation= "506", utcVariation= "UTC +1", timeZone= "Europe/Stockholm"),
        Airport(name= "São Paulo/Guarulhos International Airport", iata= "GRU", icao= "SBGR", latLong= "-23.4356, -46.4731", elevation= "2461", utcVariation= "UTC -3", timeZone= "America/Sao_Paulo"),
        Airport(name= "La Aurora International Airport", iata= "GUA", icao= "MGGT", latLong= "14.5833, -90.5275", elevation= "4952", utcVariation= "UTC -6", timeZone= "America/Guatemala"),
        Airport(name= "Geneva Airport", iata= "GVA", icao= "LSGG", latLong= "46.2381, 6.1089", elevation= "1411", utcVariation= "UTC +1", timeZone= "Europe/Zurich"),
        Airport(name= "José Joaquín de Olmedo International Airport", iata= "GYE", icao= "SEGU", latLong= "-2.1574, -79.8836", elevation= "19", utcVariation= "UTC -5", timeZone= "America/Guayaquil"),
        Airport(name= "Hong Kong International Airport", iata= "HKG", icao= "VHHH", latLong= "22.3089, 113.9146", elevation= "28", utcVariation= "UTC +8", timeZone= "Asia/Hong_Kong"),
        Airport(name= "Phuket International Airport", iata= "HKT", icao= "VTSP", latLong= "8.1132, 98.3162", elevation= "82", utcVariation= "UTC +7", timeZone= "Asia/Bangkok"),
        Airport(name= "Daniel K. Inouye International Airport", iata= "HNL", icao= "PHNL", latLong= "21.3187, -157.9225", elevation= "13", utcVariation= "UTC -10", timeZone= "Pacific/Honolulu"),
        Airport(name= "William P. Hobby Airport", iata= "HOU", icao= "KHOU", latLong= "29.6454, -95.2789", elevation= "46", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Washington Dulles International Airport", iata= "IAD", icao= "KIAD", latLong= "38.9531, -77.4565", elevation= "313", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "George Bush Intercontinental Airport", iata= "IAH", icao= "KIAH", latLong= "29.9902, -95.3368", elevation= "97", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Incheon International Airport", iata= "ICN", icao= "RKSI", latLong= "37.4602, 126.4407", elevation= "23", utcVariation= "UTC +9", timeZone= "Asia/Seoul"),
        Airport(name= "Istanbul Airport", iata= "IST", icao= "LTFM", latLong= "41.2753, 28.7519", elevation= "325", utcVariation= "UTC +3", timeZone= "Europe/Istanbul"),
        Airport(name= "King Abdulaziz International Airport", iata= "JED", icao= "OEJN", latLong= "21.6796, 39.1565", elevation= "48", utcVariation= "UTC +3", timeZone= "Asia/Riyadh"),
        Airport(name= "John F. Kennedy International Airport", iata= "JFK", icao= "KJFK", latLong= "40.6413, -73.7781", elevation= "13", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "O. R. Tambo International Airport", iata= "JNB", icao= "FAOR", latLong= "-26.1337, 28.2313", elevation= "5558", utcVariation= "UTC +2", timeZone= "Africa/Johannesburg"),
        Airport(name= "Boryspil International Airport", iata= "KBP", icao= "UKBB", latLong= "50.3450, 30.8947", elevation= "427", utcVariation= "UTC +2", timeZone= "Europe/Kiev"),
        Airport(name= "Keflavík International Airport", iata= "KEF", icao= "BIKF", latLong= "63.9850, -22.6056", elevation= "171", utcVariation= "UTC 0", timeZone= "Atlantic/Reykjavik"),
        Airport(name= "Kigali International Airport", iata= "KGL", icao= "HRYR", latLong= "-1.9686, 30.1395", elevation= "4859", utcVariation= "UTC +2", timeZone= "Africa/Kigali"),
        Airport(name= "Kansai International Airport", iata= "KIX", icao= "RJBB", latLong= "34.4342, 135.2440", elevation= "17", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Kuala Lumpur International Airport", iata= "KUL", icao= "WMKK", latLong= "2.7456, 101.7092", elevation= "70", utcVariation= "UTC +8", timeZone= "Asia/Kuala_Lumpur"),
        Airport(name= "McCarran International Airport", iata= "LAS", icao= "KLAS", latLong= "36.0801, -115.1522", elevation= "2181", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "Los Angeles International Airport", iata= "LAX", icao= "KLAX", latLong= "33.9416, -118.4085", elevation= "125", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "LaGuardia Airport", iata= "LGA", icao= "KLGA", latLong= "40.7769, -73.8740", elevation= "21", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Heathrow Airport", iata= "LHR", icao= "EGLL", latLong= "51.4700, -0.4543", elevation= "83", utcVariation= "UTC 0", timeZone= "Europe/London"),
        Airport(name= "Jorge Chávez International Airport", iata= "LIM", icao= "SPJC", latLong= "-12.0219, -77.1143", elevation= "113", utcVariation= "UTC -5", timeZone= "America/Lima"),
        Airport(name= "Humberto Delgado Airport", iata= "LIS", icao= "LPPT", latLong= "38.7756, -9.1354", elevation= "374", utcVariation= "UTC 0", timeZone= "Europe/Lisbon"),
        Airport(name= "Murtala Muhammed International Airport", iata= "LOS", icao= "DNMM", latLong= "6.5774, 3.3212", elevation= "135", utcVariation= "UTC +1", timeZone= "Africa/Lagos"),
        Airport(name= "Adolfo Suárez Madrid–Barajas Airport", iata= "MAD", icao= "LEMD", latLong= "40.4983, -3.5676", elevation= "2000", utcVariation= "UTC +1", timeZone= "Europe/Madrid"),
        Airport(name= "Manchester Airport", iata= "MAN", icao= "EGCC", latLong= "53.3658, -2.2728", elevation= "257", utcVariation= "UTC 0", timeZone= "Europe/London"),
        Airport(name= "Kansas City International Airport", iata= "MCI", icao= "KMCI", latLong= "39.2976, -94.7139", elevation= "1026", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Orlando International Airport", iata= "MCO", icao= "KMCO", latLong= "28.4294, -81.3089", elevation= "96", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Chicago Midway International Airport", iata= "MDW", icao= "KMDW", latLong= "41.7868, -87.7522", elevation= "620", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Memphis International Airport", iata= "MEM", icao= "KMEM", latLong= "35.0425, -89.9767", elevation= "341", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Mexico City International Airport", iata= "MEX", icao= "MMMX", latLong= "19.4361, -99.0719", elevation= "7316", utcVariation= "UTC -6", timeZone= "America/Mexico_City"),
        Airport(name= "Miami International Airport", iata= "MIA", icao= "KMIA", latLong= "25.7959, -80.2870", elevation= "8", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Malta International Airport", iata= "MLA", icao= "LMML", latLong= "35.8575, 14.4775", elevation= "300", utcVariation= "UTC +1", timeZone= "Europe/Malta"),
        Airport(name= "Ninoy Aquino International Airport", iata= "MNL", icao= "RPLL", latLong= "14.5086, 121.0194", elevation= "75", utcVariation= "UTC +8", timeZone= "Asia/Manila"),
        Airport(name= "Munich Airport", iata= "MUC", icao= "EDDM", latLong= "48.3538, 11.7861", elevation= "1487", utcVariation= "UTC +1", timeZone= "Europe/Berlin"),
        Airport(name= "Milan Malpensa Airport", iata= "MXP", icao= "LIMC", latLong= "45.6301, 8.7231", elevation= "768", utcVariation= "UTC +1", timeZone= "Europe/Rome"),
        Airport(name= "Jomo Kenyatta International Airport", iata= "NBO", icao= "HKJK", latLong= "-1.3192, 36.9278", elevation= "5330", utcVariation= "UTC +3", timeZone= "Africa/Nairobi"),
        Airport(name= "Nice Côte d’Azur Airport", iata= "NCE", icao= "LFMN", latLong= "43.6584, 7.2150", elevation= "12", utcVariation= "UTC +1", timeZone= "Europe/Paris"),
        Airport(name= "Chubu Centrair International Airport", iata= "NGO", icao= "RJGG", latLong= "34.8583, 136.8053", elevation= "15", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Narita International Airport", iata= "NRT", icao= "RJAA", latLong= "35.7647, 140.3864", elevation= "141", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Oakland International Airport", iata= "OAK", icao= "KOAK", latLong= "37.7126, -122.2197", elevation= "9", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "O’Hare International Airport", iata= "ORD", icao= "KORD", latLong= "41.9742, -87.9073", elevation= "672", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Orly Airport", iata= "ORY", icao= "LFPO", latLong= "48.7253, 2.3592", elevation= "291", utcVariation= "UTC +1", timeZone= "Europe/Paris"),
        Airport(name= "Oslo Gardermoen Airport", iata= "OSL", icao= "ENGM", latLong= "60.1939, 11.1004", elevation= "681", utcVariation= "UTC +1", timeZone= "Europe/Oslo"),
        Airport(name= "Henri Coandă International Airport", iata= "OTP", icao= "LROP", latLong= "44.5721, 26.1022", elevation= "314", utcVariation= "UTC +2", timeZone= "Europe/Bucharest"),
        Airport(name= "Portland International Airport", iata= "PDX", icao= "KPDX", latLong= "45.5898, -122.5951", elevation= "30", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "Beijing Capital International Airport", iata= "PEK", icao= "ZBAA", latLong= "40.0801, 116.5846", elevation= "116", utcVariation= "UTC +8", timeZone= "Asia/Shanghai"),
        Airport(name= "Philadelphia International Airport", iata= "PHL", icao= "KPHL", latLong= "39.8744, -75.2424", elevation= "36", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Phoenix Sky Harbor International Airport", iata= "PHX", icao= "KPHX", latLong= "33.4342, -112.0115", elevation= "1135", utcVariation= "UTC -7", timeZone= "America/Phoenix"),
        Airport(name= "Pittsburgh International Airport", iata= "PIT", icao= "KPIT", latLong= "40.4915, -80.2329", elevation= "1203", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Palma de Mallorca Airport", iata= "PMI", icao= "LEPA", latLong= "39.5517, 2.7388", elevation= "27", utcVariation= "UTC +1", timeZone= "Europe/Madrid"),
        Airport(name= "Václav Havel Airport Prague", iata= "PRG", icao= "LKPR", latLong= "50.1008, 14.2632", elevation= "1247", utcVariation= "UTC +1", timeZone= "Europe/Prague"),
        Airport(name= "Tocumen International Airport", iata= "PTY", icao= "MPTO", latLong= "9.0714, -79.3835", elevation= "135", utcVariation= "UTC -5", timeZone= "America/Panama"),
        Airport(name= "Punta Cana International Airport", iata= "PUJ", icao= "MDPC", latLong= "18.5674, -68.3634", elevation= "40", utcVariation= "UTC -4", timeZone= "America/Santo_Domingo"),
        Airport(name= "Shanghai Pudong International Airport", iata= "PVG", icao= "ZSPD", latLong= "31.1443, 121.8083", elevation= "13", utcVariation= "UTC +8", timeZone= "Asia/Shanghai"),
        Airport(name= "Querétaro Intercontinental Airport", iata= "QRO", icao= "MMQT", latLong= "20.6173, -100.1859", elevation= "6296", utcVariation= "UTC -6", timeZone= "America/Mexico_City"),
        Airport(name= "Marrakesh Menara Airport", iata= "RAK", icao= "GMMX", latLong= "31.6069, -8.0363", elevation= "1545", utcVariation= "UTC +1", timeZone= "Africa/Casablanca"),
        Airport(name= "Raleigh-Durham International Airport", iata= "RDU", icao= "KRDU", latLong= "35.8776, -78.7875", elevation= "435", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "King Khalid International Airport", iata= "RUH", icao= "OERK", latLong= "24.9576, 46.6988", elevation= "2049", utcVariation= "UTC +3", timeZone= "Asia/Riyadh"),
        Airport(name= "San Diego International Airport", iata= "SAN", icao= "KSAN", latLong= "32.7338, -117.1933", elevation= "17", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "Comodoro Arturo Merino Benítez International Airport", iata= "SCL", icao= "SCEL", latLong= "-33.3930, -70.7858", elevation= "1555", utcVariation= "UTC -4", timeZone= "America/Santiago"),
        Airport(name= "Seattle-Tacoma International Airport", iata= "SEA", icao= "KSEA", latLong= "47.4502, -122.3088", elevation= "433", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "San Francisco International Airport", iata= "SFO", icao= "KSFO", latLong= "37.6213, -122.3790", elevation= "13", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "Tan Son Nhat International Airport", iata= "SGN", icao= "VVTS", latLong= "10.8187, 106.6519", elevation= "33", utcVariation= "UTC +7", timeZone= "Asia/Ho_Chi_Minh"),
        Airport(name= "Singapore Changi Airport", iata= "SIN", icao= "WSSS", latLong= "1.3502, 103.9940", elevation= "22", utcVariation= "UTC +8", timeZone= "Asia/Singapore"),
        Airport(name= "Juan Santamaría International Airport", iata= "SJO", icao= "MROC", latLong= "9.9939, -84.2088", elevation= "3021", utcVariation= "UTC -6", timeZone= "America/Costa_Rica"),
        Airport(name= "Luis Muñoz Marín International Airport", iata= "SJU", icao= "TJSJ", latLong= "18.4394, -66.0018", elevation= "9", utcVariation= "UTC -4", timeZone= "America/Puerto_Rico"),
        Airport(name= "Salt Lake City International Airport", iata= "SLC", icao= "KSLC", latLong= "40.7884, -111.9786", elevation= "4227", utcVariation= "UTC -7", timeZone= "America/Denver"),
        Airport(name= "Sacramento International Airport", iata= "SMF", icao= "KSMF", latLong= "38.6955, -121.5908", elevation= "27", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "John Wayne Airport", iata= "SNA", icao= "KSNA", latLong= "33.6757, -117.8678", elevation= "56", utcVariation= "UTC -8", timeZone= "America/Los_Angeles"),
        Airport(name= "Sofia Airport", iata= "SOF", icao= "LBSF", latLong= "42.6952, 23.4062", elevation= "1742", utcVariation= "UTC +2", timeZone= "Europe/Sofia"),
        Airport(name= "St. Louis Lambert International Airport", iata= "STL", icao= "KSTL", latLong= "38.7487, -90.3700", elevation= "618", utcVariation= "UTC -6", timeZone= "America/Chicago"),
        Airport(name= "Stuttgart Airport", iata= "STR", icao= "EDDS", latLong= "48.6899, 9.2210", elevation= "1276", utcVariation= "UTC +1", timeZone= "Europe/Berlin"),
        Airport(name= "Sydney Kingsford Smith Airport", iata= "SYD", icao= "YSSY", latLong= "-33.9399, 151.1753", elevation= "21", utcVariation= "UTC +10", timeZone= "Australia/Sydney"),
        Airport(name= "Toncontín International Airport", iata= "TGU", icao= "MHTG", latLong= "14.0608, -87.2172", elevation= "3294", utcVariation= "UTC -6", timeZone= "America/Tegucigalpa"),
        Airport(name= "Ben Gurion Airport", iata= "TLV", icao= "LLBG", latLong= "32.0114, 34.8866", elevation= "135", utcVariation= "UTC +2", timeZone= "Asia/Jerusalem"),
        Airport(name= "Tampa International Airport", iata= "TPA", icao= "KTPA", latLong= "27.9755, -82.5332", elevation= "26", utcVariation= "UTC -5", timeZone= "America/New_York"),
        Airport(name= "Berlin Tegel Airport", iata= "TXL", icao= "EDDT", latLong= "52.5597, 13.2877", elevation= "122", utcVariation= "UTC +1", timeZone= "Europe/Berlin"),
        Airport(name= "Mariscal Sucre International Airport", iata= "UIO", icao= "SEQM", latLong= "-0.1253, -78.3556", elevation= "7874", utcVariation= "UTC -5", timeZone= "America/Guayaquil"),
        Airport(name= "Venice Marco Polo Airport", iata= "VCE", icao= "LIPZ", latLong= "45.5053, 12.3519", elevation= "7", utcVariation= "UTC +1", timeZone= "Europe/Rome"),
        Airport(name= "Vienna International Airport", iata= "VIE", icao= "LOWW", latLong= "48.1103, 16.5697", elevation= "600", utcVariation= "UTC +1", timeZone= "Europe/Vienna"),
        Airport(name= "Warsaw Chopin Airport", iata= "WAW", icao= "EPWA", latLong= "52.1658, 20.9671", elevation= "362", utcVariation= "UTC +1", timeZone= "Europe/Warsaw"),
        Airport(name= "Edmonton International Airport", iata= "YEG", icao= "CYEG", latLong= "53.3097, -113.5806", elevation= "2373", utcVariation= "UTC -7", timeZone= "America/Edmonton"),
        Airport(name= "Halifax Stanfield International Airport", iata= "YHZ", icao= "CYHZ", latLong= "44.8808, -63.5086", elevation= "477", utcVariation= "UTC -4", timeZone= "America/Halifax"),
        Airport(name= "Ottawa Macdonald-Cartier International Airport", iata= "YOW", icao= "CYOW", latLong= "45.3225, -75.6692", elevation= "374", utcVariation= "UTC -5", timeZone= "America/Toronto"),
        Airport(name= "Québec City Jean Lesage International Airport", iata= "YQB", icao= "CYQB", latLong= "46.7911, -71.3933", elevation= "244", utcVariation= "UTC -5", timeZone= "America/Toronto"),
        Airport(name= "Montréal-Pierre Elliott Trudeau International Airport", iata= "YUL", icao= "CYUL", latLong= "45.4706, -73.7408", elevation= "118", utcVariation= "UTC -5", timeZone= "America/Toronto"),
        Airport(name= "Vancouver International Airport", iata= "YVR", icao= "CYVR", latLong= "49.1951, -123.1778", elevation= "14", utcVariation= "UTC -8", timeZone= "America/Vancouver"),
        Airport(name= "Abu Dhabi International Airport", iata= "AUH", icao= "OMAA", latLong= "24.4567, 54.6378", elevation= "88", utcVariation= "UTC +4", timeZone= "Asia/Dubai"),
        Airport(name= "Ayers Rock Airport", iata= "AYQ", icao= "YAYE", latLong= "-25.1861, 130.9756", elevation= "1626", utcVariation= "UTC +9.5", timeZone= "Australia/Darwin"),
        Airport(name= "Sultan Aji Muhammad Sulaiman Airport", iata= "BTH", icao= "WIDD", latLong= "1.1210, 104.1190", elevation= "126", utcVariation= "UTC +7", timeZone= "Asia/Jakarta"),
        Airport(name= "Brunei International Airport", iata= "BWN", icao= "WBSB", latLong= "4.9442, 114.9283", elevation= "73", utcVariation= "UTC +8", timeZone= "Asia/Brunei"),
        Airport(name= "Camden Airport", iata= "CDN", icao= "YSCN", latLong= "-34.0394, 150.6861", elevation= "230", utcVariation= "UTC +10", timeZone= "Australia/Sydney"),
        Airport(name= "Cheongju International Airport", iata= "CJJ", icao= "RKTU", latLong= "36.7170, 127.4980", elevation= "190", utcVariation= "UTC +9", timeZone= "Asia/Seoul"),
        Airport(name= "Jeju International Airport", iata= "CJU", icao= "RKPC", latLong= "33.5113, 126.4931", elevation= "118", utcVariation= "UTC +9", timeZone= "Asia/Seoul"),
        Airport(name= "Coorabie Airport", iata= "CRJ", icao= "YCBY", latLong= "-31.8775, 132.5406", elevation= "11", utcVariation= "UTC +9.5", timeZone= "Australia/Adelaide"),
        Airport(name= "New Chitose Airport", iata= "CTS", icao= "RJCC", latLong= "42.7752, 141.6923", elevation= "70", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Curry Airport", iata= "CUR", icao= "YCUY", latLong= "-25.6475, 142.6581", elevation= "650", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Da Nang International Airport", iata= "DAD", icao= "VVDN", latLong= "16.0439, 108.1995", elevation= "33", utcVariation= "UTC +7", timeZone= "Asia/Ho_Chi_Minh"),
        Airport(name= "RAAF Base Curtin", iata= "DCN", icao= "YCIN", latLong= "-17.5806, 123.8294", elevation= "300", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Don Mueang International Airport", iata= "DMK", icao= "VTBD", latLong= "13.9126, 100.6075", elevation= "9", utcVariation= "UTC +7", timeZone= "Asia/Bangkok"),
        Airport(name= "Ngurah Rai International Airport", iata= "DPS", icao= "WADD", latLong= "-8.7486, 115.1672", elevation= "14", utcVariation= "UTC +8", timeZone= "Asia/Makassar"),
        Airport(name= "Dunedin Airport", iata= "DUD", icao= "NZDN", latLong= "-45.9281, 170.1983", elevation= "4", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Francisco Bangoy International Airport", iata= "DVO", icao= "RPMD", latLong= "7.1255, 125.6460", elevation= "59", utcVariation= "UTC +8", timeZone= "Asia/Manila"),
        Airport(name= "Esperance Airport", iata= "ESL", icao= "YESP", latLong= "-33.6844, 121.8233", elevation= "470", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Fukuoka Airport", iata= "FUK", icao= "RJFF", latLong= "33.5860, 130.4510", elevation= "33", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Geraldton Airport", iata= "GET", icao= "YGEL", latLong= "-28.7961, 114.7078", elevation= "121", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Guam International Airport", iata= "GUM", icao= "PGUM", latLong= "13.4833, 144.7933", elevation= "298", utcVariation= "UTC +10", timeZone= "Pacific/Guam"),
        Airport(name= "Hamburg Airport", iata= "HAM", icao= "EDDH", latLong= "53.6304, 9.9882", elevation= "53", utcVariation= "UTC +1", timeZone= "Europe/Berlin"),
        Airport(name= "Hihifo Airport", iata= "HIH", icao= "NFTL", latLong= "-15.9772, -173.7925", elevation= "7", utcVariation= "UTC +13", timeZone= "Pacific/Tongatapu"),
        Airport(name= "Tokyo Haneda Airport", iata= "HND", icao= "RJTT", latLong= "35.5494, 139.7798", elevation= "21", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Invercargill Airport", iata= "IVC", icao= "NZNV", latLong= "-46.4122, 168.3128", elevation= "5", utcVariation= "UTC +12", timeZone= "Pacific/Auckland"),
        Airport(name= "Senai International Airport", iata= "JHB", icao= "WMKJ", latLong= "1.6406, 103.6696", elevation= "135", utcVariation= "UTC +8", timeZone= "Asia/Kuala_Lumpur"),
        Airport(name= "Krabi International Airport", iata= "KBV", icao= "VTSG", latLong= "8.0973, 98.9862", elevation= "82", utcVariation= "UTC +7", timeZone= "Asia/Bangkok"),
        Airport(name= "Kota Kinabalu International Airport", iata= "BKI", icao= "WBKK", latLong= "5.9372, 116.0515", elevation= "10", utcVariation= "UTC +8", timeZone= "Asia/Kuala_Lumpur"),
        Airport(name= "Kuching International Airport", iata= "KCH", icao= "WBGG", latLong= "1.4847, 110.3470", elevation= "89", utcVariation= "UTC +8", timeZone= "Asia/Kuala_Lumpur"),
        Airport(name= "Kaohsiung International Airport", iata= "KHH", icao= "RCKH", latLong= "22.5725, 120.3500", elevation= "30", utcVariation= "UTC +8", timeZone= "Asia/Taipei"),
        Airport(name= "Kalgoorlie-Boulder Airport", iata= "KGI", icao= "YPKG", latLong= "-30.7894, 121.4622", elevation= "1203", utcVariation= "UTC +8", timeZone= "Australia/Perth"),
        Airport(name= "Frans Kaisiepo Airport", iata= "BIK", icao= "WABB", latLong= "-1.1900, 136.1086", elevation= "46", utcVariation= "UTC +9", timeZone= "Asia/Jayapura"),
        Airport(name= "Ellison Onizuka Kona International Airport", iata= "KOA", icao= "PHKO", latLong= "19.7388, -156.0456", elevation= "47", utcVariation= "UTC -10", timeZone= "Pacific/Honolulu"),
        Airport(name= "RAAF Base Tindal", iata= "KTR", icao= "YPTN", latLong= "-14.5211, 132.3789", elevation= "443", utcVariation= "UTC +9.5", timeZone= "Australia/Darwin"),
        Airport(name= "Kupang Airport", iata= "KUP", icao= "WATT", latLong= "-10.1711, 123.6717", elevation= "335", utcVariation= "UTC +8", timeZone= "Asia/Makassar"),
        Airport(name= "Lombok International Airport", iata= "LOP", icao= "WADL", latLong= "-8.7573, 116.2767", elevation= "52", utcVariation= "UTC +8", timeZone= "Asia/Makassar"),
        Airport(name= "Marshall Islands International Airport", iata= "MAJ", icao= "PKMJ", latLong= "7.0648, 171.2722", elevation= "6", utcVariation= "UTC +12", timeZone= "Pacific/Majuro"),
        Airport(name= "Mildura Airport", iata= "MQL", icao= "YMIA", latLong= "-34.2292, 142.0864", elevation= "167", utcVariation= "UTC +10", timeZone= "Australia/Sydney"),
        Airport(name= "Norfolk Island Airport", iata= "NLK", icao= "YSNF", latLong= "-29.0416, 167.9388", elevation= "371", utcVariation= "UTC +11", timeZone= "Pacific/Norfolk"),
        Airport(name= "La Tontouta International Airport", iata= "NOU", icao= "NWWW", latLong= "-22.0146, 166.2120", elevation= "52", utcVariation= "UTC +11", timeZone= "Pacific/Noumea"),
        Airport(name= "Kadena Air Base", iata= "OKA", icao= "RODN", latLong= "26.3556, 127.7686", elevation= "144", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Penang International Airport", iata= "PEN", icao= "WMKP", latLong= "5.2971, 100.2770", elevation= "10", utcVariation= "UTC +8", timeZone= "Asia/Kuala_Lumpur"),
        Airport(name= "Phnom Penh International Airport", iata= "PNH", icao= "VDPP", latLong= "11.5466, 104.8444", elevation= "40", utcVariation= "UTC +7", timeZone= "Asia/Phnom_Penh"),
        Airport(name= "Port Moresby Jacksons International Airport", iata= "POM", icao= "AYPY", latLong= "-9.4434, 147.2200", elevation= "146", utcVariation= "UTC +10", timeZone= "Pacific/Port_Moresby"),
        Airport(name= "Faa’a International Airport", iata= "PPT", icao= "NTAA", latLong= "-17.5537, -149.6064", elevation= "5", utcVariation= "UTC -10", timeZone= "Pacific/Tahiti"),
        Airport(name= "Rockhampton Airport", iata= "ROK", icao= "YBRK", latLong= "-23.3819, 150.4753", elevation= "36", utcVariation= "UTC +10", timeZone= "Australia/Brisbane"),
        Airport(name= "Sendai Airport", iata= "SDJ", icao= "RJSS", latLong= "38.1397, 140.9169", elevation= "6", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Saipan International Airport", iata= "SPN", icao= "PGSN", latLong= "15.1190, 145.7290", elevation= "215", utcVariation= "UTC +10", timeZone= "Pacific/Saipan"),
        Airport(name= "Suvarnabhumi Airport", iata= "BKK", icao= "VTBS", latLong= "13.6923, 100.7514", elevation= "5", utcVariation= "UTC +7", timeZone= "Asia/Bangkok"),
        Airport(name= "Naha Airport", iata= "OKA", icao= "ROAH", latLong= "26.1958, 127.6450", elevation= "12", utcVariation= "UTC +9", timeZone= "Asia/Tokyo"),
        Airport(name= "Sultan Hasanuddin International Airport", iata= "UPG", icao= "WAAA", latLong= "-5.0616, 119.5540", elevation= "47", utcVariation= "UTC +8", timeZone= "Asia/Makassar"),
        Airport(name= "Taipei Taoyuan International Airport", iata= "TPE", icao= "RCTP", latLong= "25.0777, 121.2320", elevation= "106", utcVariation= "UTC +8", timeZone= "Asia/Taipei"),
        Airport(name= "RAAF Base Tindal", iata= "TDL", icao= "YPTN", latLong= "-14.5211, 132.3789", elevation= "443", utcVariation= "UTC +9.5", timeZone= "Australia/Darwin")
    )

    val companyAirports = listOf(
        Airport(name = " Greenwich", iata = "UTC", icao = "GMT", latLong = "51.4769,0", elevation = "0", utcVariation = "UTC +0", timeZone = "UTC"),
        Airport(name = "Adelaide Airport", iata = "ADL", icao = "YPAD", latLong = "-34.9450, 138.5306", elevation = "20", utcVariation = "UTC +9.5", timeZone = "Australia/Adelaide"),
        Airport(name = "Auckland Airport", iata = "AKL", icao = "NZAA", latLong = "-37.0081, 174.7917", elevation = "23", utcVariation = "UTC +12", timeZone = "Pacific/Auckland"),
        Airport(name = "Avalon Airport", iata = "AVV", icao = "YMAV", latLong = "-38.0394, 144.4686", elevation = "35", utcVariation = "UTC +10", timeZone = "Australia/Melbourne"),
        Airport(name = "Ayers Rock Airport", iata = "AYQ", icao = "YAYE", latLong = "-25.1861, 130.9756", elevation = "1626", utcVariation = "UTC +9.5", timeZone = "Australia/Darwin"),
        Airport(name = "Ngurah Rai International Airport", iata = "DPS", icao = "WADD", latLong = "-8.7486, 115.1672", elevation = "14", utcVariation = "UTC +8", timeZone = "Asia/Makassar"),
        Airport(name = "Ballina Byron Gateway Airport", iata = "BNK", icao = "YBNA", latLong = "-28.8339, 153.5622", elevation = "7", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Brisbane Airport", iata = "BNE", icao = "YBBN", latLong = "-27.3842, 153.1175", elevation = "13", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Busselton Margaret River Airport", iata = "BQB", icao = "YBLN", latLong = "-33.6875, 115.4000", elevation = "55", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Cairns Airport", iata = "CNS", icao = "YBCS", latLong = "-16.8858, 145.7552", elevation = "10", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Christchurch International Airport", iata = "CHC", icao = "NZCH", latLong = "-43.4889, 172.5335", elevation = "123", utcVariation = "UTC +12", timeZone = "Pacific/Auckland"),
        Airport(name = "Darwin International Airport", iata = "DRW", icao = "YPDN", latLong = "-12.4147, 130.8767", elevation = "103", utcVariation = "UTC +9.5", timeZone = "Australia/Darwin"),
        Airport(name = "Dunedin Airport", iata = "DUD", icao = "NZDN", latLong = "-45.9281, 170.1983", elevation = "4", utcVariation = "UTC +12", timeZone = "Pacific/Auckland"),
        Airport(name = "Gold Coast Airport", iata = "OOL", icao = "YBCG", latLong = "-28.1644, 153.5047", elevation = "21", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Hamilton Island Airport", iata = "HTI", icao = "YBHM", latLong = "-20.3581, 148.9511", elevation = "15", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Fraser Coast Airport", iata = "HVB", icao = "YHBA", latLong = "-25.3189, 152.8800", elevation = "61", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Hobart International Airport", iata = "HBA", icao = "YMHB", latLong = "-42.8361, 147.5094", elevation = "13", utcVariation = "UTC +10", timeZone = "Australia/Hobart"),
        Airport(name = "Melbourne Airport", iata = "MEL", icao = "YMML", latLong = "-37.6733, 144.8433", elevation = "434", utcVariation = "UTC +10", timeZone = "Australia/Melbourne"),
        Airport(name = "Newcastle Airport", iata = "NTL", icao = "YWLM", latLong = "-32.7947, 151.8330", elevation = "31", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Nadi International Airport", iata = "NAN", icao = "NFFN", latLong = "-17.7554, 177.4433", elevation = "59", utcVariation = "UTC +12", timeZone = "Pacific/Fiji"),
        Airport(name = "Perth Airport", iata = "PER", icao = "YPPH", latLong = "-31.9403, 115.9667", elevation = "67", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Proserpine/Whitsunday Coast Airport", iata = "PPP", icao = "YBPN", latLong = "-20.4950, 148.5522", elevation = "79", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Rarotonga International Airport", iata = "RAR", icao = "NCRG", latLong = "-21.2022, -159.8056", elevation = "19", utcVariation = "UTC -10", timeZone = "Pacific/Rarotonga"),
        Airport(name = "Singapore Changi Airport", iata = "SIN", icao = "WSSS", latLong = "1.3502, 103.9940", elevation = "22", utcVariation = "UTC +8", timeZone = "Asia/Singapore"),
        Airport(name = "Sunshine Coast Airport", iata = "MCY", icao = "YBSU", latLong = "-26.6033, 153.0910", elevation = "15", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Sydney Kingsford Smith Airport", iata = "SYD", icao = "YSSY", latLong = "-33.9399, 151.1753", elevation = "21", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Invercargill Airport", iata = "IVC", icao = "NZNV", latLong = "-46.4122, 168.3128", elevation = "5", utcVariation = "UTC +12", timeZone = "Pacific/Auckland"),
        Airport(name = "Soekarno-Hatta International Airport", iata = "CGK", icao = "WIII", latLong = "-6.1256, 106.6559", elevation = "34", utcVariation = "UTC +7", timeZone = "Asia/Jakarta"),
        Airport(name = "Senai International Airport", iata = "JHB", icao = "WMKJ", latLong = "1.6406, 103.6696", elevation = "135", utcVariation = "UTC +8", timeZone = "Asia/Kuala_Lumpur"),
        Airport(name = "Kalgoorlie-Boulder Airport", iata = "KGI", icao = "YPKG", latLong = "-30.7894, 121.4622", elevation = "1203", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Karratha Airport", iata = "KTA", icao = "YPKA", latLong = "-20.7122, 116.7731", elevation = "29", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Kuala Lumpur International Airport", iata = "KUL", icao = "WMKK", latLong = "2.7456, 101.7092", elevation = "70", utcVariation = "UTC +8", timeZone = "Asia/Kuala_Lumpur"),
        Airport(name = "Kununurra Airport", iata = "KNX", icao = "YPKU", latLong = "-15.7781, 128.7075", elevation = "145", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Launceston Airport", iata = "LST", icao = "YMLT", latLong = "-41.5453, 147.2144", elevation = "562", utcVariation = "UTC +10", timeZone = "Australia/Hobart"),
        Airport(name = "Lombok International Airport", iata = "LOP", icao = "WADL", latLong = "-8.7573, 116.2767", elevation = "52", utcVariation = "UTC +8", timeZone = "Asia/Makassar"),
        Airport(name = "Makassar Airport", iata = "UPG", icao = "WAAA", latLong = "-5.0616, 119.5540", elevation = "47", utcVariation = "UTC +8", timeZone = "Asia/Mqueeakassar"),
        Airport(name = "Mildura Airport", iata = "MQL", icao = "YMIA", latLong = "-34.2292, 142.0864", elevation = "167", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Nadi International Airport", iata = "NAN", icao = "NFNA", latLong = "-17.7554, 177.4433", elevation = "59", utcVariation = "UTC +12", timeZone = "Pacific/Fiji"),
        Airport(name = "Norfolk Island Airport", iata = "NLK", icao = "YNWN", latLong = "-29.0416, 167.9388", elevation = "371", utcVariation = "UTC +11", timeZone = "Pacific/Norfolk"),
        Airport(name = "La Tontouta International Airport", iata = "NOU", icao = "NWWW", latLong = "-22.0146, 166.2120", elevation = "52", utcVariation = "UTC +11", timeZone = "Pacific/Noumea"),
        Airport(name = "Fuaʻamotu International Airport", iata = "TBU", icao = "NFTF", latLong = "-21.2412, -175.1498", elevation = "125", utcVariation = "UTC +13", timeZone = "Pacific/Tongatapu"),
        Airport(name = "Palmerston North Airport", iata = "PMR", icao = "NZPM", latLong = "-40.3206, 175.6169", elevation = "151", utcVariation = "UTC +12", timeZone = "Pacific/Auckland"),
        Airport(name = "Penang International Airport", iata = "PEN", icao = "WMKP", latLong = "5.2971, 100.2770", elevation = "10", utcVariation = "UTC +8", timeZone = "Asia/Kuala_Lumpur"),
        Airport(name = "Port Hedland International Airport", iata = "PHE", icao = "YPPD", latLong = "-20.3778, 118.6253", elevation = "33", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Rockhampton Airport", iata = "ROK", icao = "YBRK", latLong = "-23.3819, 150.4753", elevation = "36", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Townsville Airport", iata = "TSV", icao = "YBTL", latLong = "-19.2525, 146.7647", elevation = "18", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Warrnambool Airport", iata = "WMB", icao = "YWBL", latLong = "-38.2964, 142.4486", elevation = "242", utcVariation = "UTC +10", timeZone = "Australia/Melbourne"),
        Airport(name = "Faa’a International Airport", iata = "PPT", icao = "NTAA", latLong = "-17.5537, -149.6064", elevation = "5", utcVariation = "UTC -10", timeZone = "Pacific/Tahiti"),
        Airport(name = "Curtin Airport", iata = "DCN", icao = "YCIN", latLong = "-17.5806, 123.8294", elevation = "300", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Esperance Airport", iata = "EPR", icao = "YESP", latLong = "-33.6844, 121.8233", elevation = "470", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Kingscote Airport", iata = "KGC", icao = "YKSC", latLong = "-35.7139, 137.5206", elevation = "24", utcVariation = "UTC +9.5", timeZone = "Australia/Adelaide"),
        Airport(name = "El Tari Airport", iata = "KOE", icao = "WATT", latLong = "-10.1711, 123.6717", elevation = "335", utcVariation = "UTC +8", timeZone = "Asia/Makassar"),
        Airport(name = "Learmonth Airport", iata = "LEA", icao = "YPLM", latLong = "-22.2356, 114.0894", elevation = "19", utcVariation = "UTC +8", timeZone = "Australia/Perth"),
        Airport(name = "Longreach Airport", iata = "LRE", icao = "YLRE", latLong = "-23.4342, 144.2797", elevation = "627", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Mareeba Airport", iata = "MRG", icao = "YMBA", latLong = "-17.0694, 145.4194", elevation = "1553", utcVariation = "UTC +10", timeZone = "Australia/Brisbane"),
        Airport(name = "Nelson Airport", iata = "NSN", icao = "YSNS", latLong = "-41.2983, 173.2219", elevation = "17", utcVariation = "UTC +12", timeZone = "Pacific/Auckland"),
        Airport(name = "Tamworth Airport", iata = "TMW", icao = "YSTW", latLong = "-31.0839, 150.8464", elevation = "1334", utcVariation = "UTC +10", timeZone = "Australia/Sydney"),
        Airport(name = "Tindal Airport", iata = "KTR", icao = "YPTN", latLong = "-14.5211, 132.3789", elevation = "443", utcVariation = "UTC +9.5", timeZone = "Australia/Darwin"),
        Airport(name = "Wellington International Airport", iata = "WLG", icao = "NZWN", latLong = "-41.3272, 174.8053", elevation = "41", utcVariation = "UTC +12", timeZone = "Pacific/Auckland"),
        Airport(name = "RAAF Base Woomera", iata = "UMR", icao = "YPWR", latLong = "-31.1442, 136.8153", elevation = "554", utcVariation = "UTC +9.5", timeZone = "Australia/Adelaide"),

        // 787 ports
        Airport(name = "Suvarnabhumi Airport", iata = "BKK", icao = "VTBS", latLong = "13.6923, 100.7514", elevation = "5", utcVariation = "UTC +7", timeZone = "Asia/Bangkok"),
        Airport(name = "Tan Son Nhat International Airport", iata = "SGN", icao = "VVTS", latLong = "10.8187, 106.6519", elevation = "33", utcVariation = "UTC +7", timeZone = "Asia/Ho_Chi_Minh"),
        Airport(name = "Daniel K. Inouye International Airport", iata = "HNL", icao = "PHNL", latLong = "21.3187, -157.9225", elevation = "13", utcVariation = "UTC -10", timeZone = "Pacific/Honolulu"),
        Airport(name = "Kansai International Airport", iata = "KIX", icao = "RJBB", latLong = "34.4342, 135.2440", elevation = "17", utcVariation = "UTC +9", timeZone = "Asia/Tokyo"),
        Airport(name = "Phuket International Airport", iata = "HKT", icao = "VTSP", latLong = "8.1132, 98.3162", elevation = "82", utcVariation = "UTC +7", timeZone = "Asia/Bangkok"),
        Airport(name = "Incheon International Airport", iata = "ICN", icao = "RKSI", latLong = "37.4602, 126.4407", elevation = "23", utcVariation = "UTC +9", timeZone = "Asia/Seoul"),
        Airport(name = "Narita International Airport", iata = "NRT", icao = "RJAA", latLong = "35.7647, 140.3864", elevation = "141", utcVariation = "UTC +9", timeZone = "Asia/Tokyo"),
        Airport(name = "Brunei International Airport", iata = "BWN", icao = "WBSB", latLong = "4.9442, 114.9283", elevation = "73", utcVariation = "UTC +8", timeZone = "Asia/Brunei"),
        Airport(name = "Don Mueang International Airport", iata = "DMK", icao = "VTBD", latLong = "13.9126, 100.6075", elevation = "9", utcVariation = "UTC +7", timeZone = "Asia/Bangkok"),
        Airport(name = "Cheongju International Airport", iata = "CJJ", icao = "RKTU", latLong = "36.7170, 127.4980", elevation = "190", utcVariation = "UTC +9", timeZone = "Asia/Seoul"),
        Airport(name = "Da Nang International Airport", iata = "DAD", icao = "VVDN", latLong = "16.0439, 108.1995", elevation = "33", utcVariation = "UTC +7", timeZone = "Asia/Ho_Chi_Minh"),
        Airport(name = "Fukuoka Airport", iata = "FUK", icao = "RJFF", latLong = "33.5860, 130.4510", elevation = "33", utcVariation = "UTC +9", timeZone = "Asia/Tokyo"),
        Airport(name = "Hong Kong International Airport", iata = "HKG", icao = "VHHH", latLong = "22.3089, 113.9146", elevation = "28", utcVariation = "UTC +8", timeZone = "Asia/Hong_Kong"),
        Airport(name = "Jeju International Airport", iata = "CJU", icao = "RKPC", latLong = "33.5113, 126.4931", elevation = "118", utcVariation = "UTC +9", timeZone = "Asia/Seoul"),
        Airport(name = "Kahului Airport", iata = "OGG", icao = "PHOG", latLong = "20.8986, -156.4306", elevation = "54", utcVariation = "UTC -10", timeZone = "Pacific/Honolulu"),
        Airport(name = "Ellison Onizuka Kona International Airport", iata = "KOA", icao = "PHKO", latLong = "19.7388, -156.0456", elevation = "47", utcVariation = "UTC -10", timeZone = "Pacific/Honolulu"),
        Airport(name = "Krabi International Airport", iata = "KBV", icao = "VTSG", latLong = "8.0973, 98.9862", elevation = "82", utcVariation = "UTC +7", timeZone = "Asia/Bangkok"),
        Airport(name = "Kuala Lumpur International Airport", iata = "KUL", icao = "WMKK", latLong = "2.7456, 101.7092", elevation = "70", utcVariation = "UTC +8", timeZone = "Asia/Kuala_Lumpur"),
        Airport(name = "Chubu Centrair International Airport", iata = "NGO", icao = "RJGG", latLong = "34.8583, 136.8053", elevation = "15", utcVariation = "UTC +9", timeZone = "Asia/Tokyo"),
        Airport(name = "Ohakea Airport", iata = "OHA", icao = "NZOH", latLong = "-40.2050, 175.3883", elevation = "80", utcVariation = "UTC +12", timeZone = "Pacific/Auckland"),
        Airport(name = "Phnom Penh International Airport", iata = "PNH", icao = "VDPP", latLong = "11.5466, 104.8444", elevation = "40", utcVariation = "UTC +7", timeZone = "Asia/Phnom_Penh"),
        Airport(name = "New Chitose Airport", iata = "CTS", icao = "RJCC", latLong = "42.7752, 141.6923", elevation = "70", utcVariation = "UTC +9", timeZone = "Asia/Tokyo"),
        Airport(name = "Sendai Airport", iata = "SDJ", icao = "RJSS", latLong = "38.1397, 140.9169", elevation = "6", utcVariation = "UTC +9", timeZone = "Asia/Tokyo"),
        Airport(name = "Juanda International Airport", iata = "SUB", icao = "WARR", latLong = "-7.3797, 112.7871", elevation = "10", utcVariation = "UTC +7", timeZone = "Asia/Jakarta"),
        Airport(name = "Tokyo Haneda Airport", iata = "HND", icao = "RJTT", latLong = "35.5494, 139.7798", elevation = "21", utcVariation = "UTC +9", timeZone = "Asia/Tokyo"),
        Airport(name = "Frans Kaisiepo Airport", iata = "BIK", icao = "WABB", latLong = "-1.1900, 136.1086", elevation = "46", utcVariation = "UTC +9", timeZone = "Asia/Jayapura"),
        Airport(name = "Francisco Bangoy International Airport", iata = "DVO", icao = "RPMD", latLong = "7.1255, 125.6460", elevation = "59", utcVariation = "UTC +8", timeZone = "Asia/Manila"),
        Airport(name = "Guam International Airport", iata = "GUM", icao = "PGUM", latLong = "13.4833, 144.7933", elevation = "298", utcVariation = "UTC +10", timeZone = "Pacific/Guam"),
        Airport(name = "Kaohsiung International Airport", iata = "KHH", icao = "RCKH", latLong = "22.5725, 120.3500", elevation = "30", utcVariation = "UTC +8", timeZone = "Asia/Taipei"),
        Airport(name = "Kuching International Airport", iata = "KCH", icao = "WBGG", latLong = "1.4847, 110.3470", elevation = "89", utcVariation = "UTC +8", timeZone = "Asia/Kuala_Lumpur"),
        Airport(name = "Marshall Islands International Airport", iata = "MAJ", icao = "PKMJ", latLong = "7.0648, 171.2722", elevation = "6", utcVariation = "UTC +12", timeZone = "Pacific/Majuro"),
        Airport(name = "Sultan Hasanuddin International Airport", iata = "UPG", icao = "WAAA", latLong = "-5.0616, 119.5540", elevation = "47", utcVariation = "UTC +8", timeZone = "Asia/Makassar"),
        Airport(name = "Ninoy Aquino International Airport", iata = "MNL", icao = "RPLL", latLong = "14.5086, 121.0194", elevation = "75", utcVariation = "UTC +8", timeZone = "Asia/Manila"),
        Airport(name = "Naha Airport", iata = "OKA", icao = "ROAH", latLong = "26.1958, 127.6450", elevation = "12", utcVariation = "UTC +9", timeZone = "Asia/Tokyo"),
        Airport(name = "Port Moresby Jacksons International Airport", iata = "POM", icao = "AYPY", latLong = "-9.4434, 147.2200", elevation = "146", utcVariation = "UTC +10", timeZone = "Pacific/Port_Moresby"),
        Airport(name = "Saipan International Airport", iata = "SPN", icao = "PGSN", latLong = "15.1190, 145.7290", elevation = "215", utcVariation = "UTC +10", timeZone = "Pacific/Saipan"),
        Airport(name = "Taipei Taoyuan International Airport", iata = "TPE", icao = "RCTP", latLong = "25.0777, 121.2320", elevation = "106", utcVariation = "UTC +8", timeZone = "Asia/Taipei")
    )
}