package com.example.jroster

import android.content.Context
import android.net.ConnectivityManager
import android.net.NetworkCapabilities
import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.view.inputmethod.InputMethodManager
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.fragment.app.Fragment
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response
import androidx.constraintlayout.widget.ConstraintLayout
import androidx.constraintlayout.widget.ConstraintSet
import androidx.core.view.isGone
import com.google.android.material.bottomnavigation.BottomNavigationView
import kotlinx.coroutines.withContext
import kotlinx.coroutines.CoroutineScope
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class FragmentFriends : Fragment() {

    private lateinit var recyclerView: RecyclerView
    private lateinit var addFriendButton: Button
    private lateinit var friendCodeInput: EditText
    private lateinit var viewRosterButton: Button
    private lateinit var daysOffButton: Button //
    private lateinit var friendAdapter: FriendAdapter
    private lateinit var optionBox: LinearLayout
    private val daysOffCodes = listOf("OFF", "WOF", "FDO", "ROF", "7OF", "APO", "CDO", "EOF", "EWD", "FOF", "LOF", "MOF", "NDM", "NOF", "OBA", "OFR", "PHO", "POF", "RO1", "SOF", "STR", "UOF", "WDL", "WDS", "XMS", "XOF", "AOF", "A0F")

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val view = inflater.inflate(R.layout.fragment_friends, container, false)

        // Initialize UI components
        recyclerView = view.findViewById(R.id.friendRecyclerView)
        addFriendButton = view.findViewById(R.id.addFriendButton)
        friendCodeInput = view.findViewById(R.id.friendCodeInput)
        optionBox = view.findViewById(R.id.optionBox)
        viewRosterButton = view.findViewById(R.id.viewRosterButton)
        daysOffButton = view.findViewById(R.id.daysOffButton)

        // Set up RecyclerView
        recyclerView.layoutManager = LinearLayoutManager(requireContext())
        friendAdapter = FriendAdapter(
            listOf(),
            onFriendSelectedCallback = { onFriendSelected() },
            onDeleteFriendCallback = { friend -> deleteFriend(friend) }
        )

        recyclerView.adapter = friendAdapter

        // Set up Add Friend Button Listener
        addFriendButton.setOnClickListener {
            val friendCode = friendCodeInput.text.toString().trim()
            if (friendCode.length == 3) {
                checkInternetAndFetchFriend(friendCode)
            } else {
                showAlertDialog(
                    "Invalid Friend Code",
                    "Friend Codes are a 3 digit, case-sensitive code. They are generated by JTools and displayed when a user first enables 'JRoster'."
                )
            }
        }

        // Set up View Roster Button Listener
        viewRosterButton.setOnClickListener {
            viewRoster()
        }

        // Inside onCreateView or wherever the button is set up
        daysOffButton.setOnClickListener {
            if (daysOffButton.text != "Mutual Days Off") {
                restoreFriendsList()
            } else {
                // Find mutual days off and display them
                findMutualDaysOff()
            }
        }

        // Hide the optionBox initially
        optionBox.visibility = View.GONE

        // Update the table from the DB
        updateRecyclerView()

        return view
    }

    // ---------------------------------------- Adding Friends  -------------------------------------------------------------------- //

    // Step 1
    private fun checkInternetAndFetchFriend(friendCode: String) {
        if (isInternetAvailable(requireContext())) {
            if (friendCode.length == 3) {
                fetchFriendDataFromMySQL(friendCode)
            } else {
                showAlertDialog(
                    "Invalid Friend Code",
                    "Friend Codes must be a 3-character code. Please double-check and try again."
                )
            }
        } else {
            showAlertDialog(
                "No Internet Connection",
                "Sadly, it requires the combined power of the entire internet to discover if you do in fact, have any friends. Please try again once you have an internet connection."
            )
        }
    }

    // Step 2 - After fetching the friend's details, fetch their flights
    private fun fetchFriendDataFromMySQL(friendCode: String) {

        val call = RetrofitClient.friendApiService.getFriendData(friendCode)

        call.enqueue(object : Callback<List<Friend>> {
            override fun onResponse(call: Call<List<Friend>>, response: Response<List<Friend>>) {
                if (response.isSuccessful) {
                    val friendDataList = response.body()

                    if (friendDataList != null && friendDataList.isNotEmpty()) {
                        for (friend in friendDataList) {
                            // Insert friend details into the database
                            insertFriendIntoDatabase(friend)

                            // Fetch and insert the friend's flights using userID and friendCode
                            fetchFriendFlightsFromMySQL(friend.userID, friend.friendCode)
                        }
                    } else {
                        Toast.makeText(requireContext(), "No friend data found for this code", Toast.LENGTH_SHORT).show()
                    }
                } else {
                    Toast.makeText(requireContext(), "Failed to fetch friend data", Toast.LENGTH_SHORT).show()
                }
            }

            override fun onFailure(call: Call<List<Friend>>, t: Throwable) {
                Toast.makeText(requireContext(), "Error: ${t.message}", Toast.LENGTH_SHORT).show()
            }
        })
    }

    // Step 3 - Insert fetched friend data into Room database
    private fun insertFriendIntoDatabase(friend: Friend) {
        GlobalScope.launch(Dispatchers.IO) {
            val db = AppDatabase.getInstance(requireContext())
            db.friendDao().insertFriend(friend)
            launch(Dispatchers.Main) {
                // Update RecyclerView
                updateRecyclerView()

                // Clear the input field
                friendCodeInput.setText("")

                // Close the keyboard
                val imm = requireContext().getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
                imm.hideSoftInputFromWindow(friendCodeInput.windowToken, 0)

                // Show a success message
                Toast.makeText(requireContext(), "Friend added successfully", Toast.LENGTH_SHORT).show()
            }
        }
    }

    // Step 4 - Fetch friend's flights (roster) data from MySQL
    private fun fetchFriendFlightsFromMySQL(friendUserID: String, friendCode: String) {
        Log.d("MutualDaysOffDebug", "Fetching flights for friendUserID: $friendUserID, friendCode: $friendCode")

        // Call the API to fetch friend's flights
        val flightCall = RetrofitClient.rosterApiService.getFriendRosterData(friendUserID, friendCode)

        flightCall.enqueue(object : Callback<List<FriendsFlights>> {
            override fun onResponse(call: Call<List<FriendsFlights>>, response: Response<List<FriendsFlights>>) {
                if (response.isSuccessful) {
                    val flightList = response.body()

                    if (flightList != null && flightList.isNotEmpty()) {
                        insertFriendFlightsIntoDatabase(flightList, friendCode)  // Pass friendCode here
                    } else {
                        Toast.makeText(requireContext(), "No flights found for this friend", Toast.LENGTH_SHORT).show()
                    }
                } else {
                    Toast.makeText(requireContext(), "Failed to fetch friend's flights", Toast.LENGTH_SHORT).show()
                }
            }

            override fun onFailure(call: Call<List<FriendsFlights>>, t: Throwable) {
                Toast.makeText(requireContext(), "Error fetching friend's flights: ${t.message}", Toast.LENGTH_SHORT).show()
            }
        })
    }

    // Step 5 - Insert friend's flights
    private fun insertFriendFlightsIntoDatabase(flightList: List<FriendsFlights>, friendCode: String) {
        GlobalScope.launch(Dispatchers.IO) {
            try {
                val db = AppDatabase.getInstance(requireContext())

                // Ensure each flight has the friendCode set before insertion
                val flightsWithFriendCode = flightList.map { flight ->
                    flight.copy(friendCode = friendCode)  // Set friendCode if it's missing
                }

                db.friendsFlightsDao().insertAll(flightsWithFriendCode)
                Log.d("MutualDaysOffDebug", "Successfully inserted ${flightsWithFriendCode.size} flights into the database")
            } catch (e: Exception) {
                Log.e("MutualDaysOffDebug", "Error inserting flights into the database: ${e.message}")
            }
        }
    }

    // ---------------------------------------- Core Functions  -------------------------------------------------------------------- //

    // Method to handle friend selection and show the option box
    private fun onFriendSelected() {
        optionBox.visibility = View.VISIBLE

        // Modify constraints
        val constraintLayout = view?.findViewById<ConstraintLayout>(R.id.settingsLayout)
        val constraintSet = ConstraintSet()
        constraintSet.clone(constraintLayout)

        // Connect
        constraintSet.connect(
            R.id.friendRecyclerView,
            ConstraintSet.BOTTOM,
            R.id.optionBox,
            ConstraintSet.TOP
        )

        // Apply
        constraintSet.applyTo(constraintLayout)
    }

    private fun findMutualDaysOff() {
        val selectedFriend = getSelectedFriendFromDatabase()

        if (selectedFriend != null) {
            GlobalScope.launch(Dispatchers.IO) {
                val db = AppDatabase.getInstance(requireContext())

                // Get today's date in the correct format (yyyy-MM-dd)
                val dateFormatter = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
                val today = dateFormatter.format(Date())

                // Fetch friend's day-off entries from today onwards
                val friendDaysOff = db.friendsFlightsDao().getFlightsByFriendCodeAndActivityFromDate(
                    selectedFriend.friendCode,
                    daysOffCodes,
                    today
                ).map { it.date }

                // Fetch user's day-off entries from today onwards
                val userDaysOff = db.dbDataDao().getUserDaysOffFromDate(daysOffCodes, today).map { it.date }

                // Compare the two lists to find mutual days off
                val mutualDaysOff = userDaysOff.intersect(friendDaysOff).toList()

                // Create a date formatter for the desired format: "E d MMM"
                val outputDateFormatter = SimpleDateFormat("E d MMM", Locale.getDefault())

                val formattedMutualDaysOff = mutualDaysOff.map { date ->
                    val parsedDate = dateFormatter.parse(date)
                    parsedDate?.let { outputDateFormatter.format(it) } ?: date
                }

                withContext(Dispatchers.Main) {
                    // Format the mutual days off button
                    daysOffButton.text = "Exit Mutual Mode"

                    if (formattedMutualDaysOff.isNotEmpty()) {
                        // Update the RecyclerView
                        friendAdapter.updateData(formattedMutualDaysOff, isDaysOff = true)
                        recyclerView.scrollToPosition(0)
                    } else {
                        friendAdapter.updateData(listOf("No mutual days off"), isDaysOff = true)
                    }
                }
            }
        } else {
            Toast.makeText(requireContext(), "Please select a friend first.", Toast.LENGTH_SHORT).show()
        }
    }

    // ---------------------------------------- Boilerplate  -------------------------------------------------------------------- //

    // Restore the friends list when exiting mutual days off mode
    private fun restoreFriendsList() {
        daysOffButton.setText("Mutual Days Off")

        // Remove the View Roster and Mutual Days Off boxes
        optionBox.isGone = true

        // Fetch and update the RecyclerView
        GlobalScope.launch(Dispatchers.IO) {
            val db = AppDatabase.getInstance(requireContext())
            val friends = db.friendDao().getAllFriends()

            withContext(Dispatchers.Main) {
                // Update the RecyclerView
                friendAdapter.updateData(friends, isDaysOff = false)
                recyclerView.scrollToPosition(0)

                // Re-enable friend selection
                friendAdapter.notifyDataSetChanged()
            }
        }
    }

    // Delete a friend from Rooms
    private fun deleteFriend(friend: Friend) {
        AlertDialog.Builder(requireContext())
            .setTitle("Delete Friend")
            .setMessage("Are you sure you want to delete ${friend.name}?")
            .setPositiveButton("Yes") { dialog, _ ->
                // Delete friend from the database
                CoroutineScope(Dispatchers.IO).launch {
                    val db = AppDatabase.getInstance(requireContext())
                    db.friendDao().deleteFriend(friend.friendCode)

                    withContext(Dispatchers.Main) {
                        // Reload RecyclerView after deletion
                        updateRecyclerView()
                        Toast.makeText(requireContext(), "${friend.name} deleted", Toast.LENGTH_SHORT).show()
                    }
                }
                dialog.dismiss()
            }
            .setNegativeButton("No") { dialog, _ -> dialog.dismiss() }
            .create()
            .show()
    }

    // Update RecyclerView with data from Room database
    private fun updateRecyclerView() {
        GlobalScope.launch(Dispatchers.IO) {
            val db = AppDatabase.getInstance(requireContext())
            val friends = db.friendDao().getAllFriends()
            launch(Dispatchers.Main) {
                // Bit of a hack but it works
                friendAdapter.updateData(friends, isDaysOff = false)
            }
        }
    }

    // Check if internet is available
    private fun isInternetAvailable(context: Context): Boolean {
        val connectivityManager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
        val activeNetwork = connectivityManager.activeNetwork ?: return false
        val networkCapabilities = connectivityManager.getNetworkCapabilities(activeNetwork) ?: return false
        return networkCapabilities.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
    }

    // Show alert dialog for errors
    private fun showAlertDialog(title: String, message: String) {
        AlertDialog.Builder(requireContext())
            .setTitle(title)
            .setMessage(message)
            .setPositiveButton("OK", null)
            .show()
    }

    // Access the global vars
    private fun returnFriendsDetails(selectedFriend: Friend) {
        GlobalVariables.globalFriendUserID = selectedFriend.userID
        GlobalVariables.globalFriendCode = selectedFriend.friendCode
        GlobalVariables.globalFriendName = selectedFriend.name
        GlobalVariables.isFriendMode = true
    }

    fun saveSelectedFriendDetails(context: Context, friendID: String, friendCode: String, friendName: String) {
        // Update GlobalVariables
        GlobalVariables.globalFriendUserID = friendID
        GlobalVariables.globalFriendCode = friendCode
        GlobalVariables.globalFriendName = friendName
        GlobalVariables.isFriendMode = true
    }


    private fun viewRoster() {
        // Get the selected friend's details
        val selectedFriend = getSelectedFriendFromDatabase()

        if (selectedFriend != null) {
            // Save the selected friend's details in SharedPreferences
            saveSelectedFriendDetails(requireContext(), selectedFriend.userID, selectedFriend.friendCode, selectedFriend.name)

            // Switch to the Roster Fragment
            switchToRosterFragment()
        } else {
            Toast.makeText(requireContext(), "Please select a friend first.", Toast.LENGTH_SHORT).show()
        }
    }

    private fun getSelectedFriendFromDatabase(): Friend? {
        // Implement logic to get selected friend from database or adapter
        return friendAdapter.getSelectedFriend()
    }

    private fun switchToRosterFragment() {
        // Replace the current fragment with FragmentRoster
        val fragmentManager = parentFragmentManager
        val transaction = fragmentManager.beginTransaction()
        transaction.replace(R.id.fragment_container, FragmentRoster())
        transaction.addToBackStack(null)
        transaction.commit()

        // Make sure the roster tab highlights
        val bottomNavigationView = requireActivity().findViewById<BottomNavigationView>(R.id.bottomNavigationView)
        bottomNavigationView.selectedItemId = R.id.nav_roster
    }
}
